version: '3.7'
services:
  db-customer:
    restart: always
    build: 
      context: .
      target: db-customer
    image: msdemo-db-customer:v1.0
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${DB_PORT}:6379"
    volumes:          
      - type: bind
        source: ./data
        target: /data   
    networks:
      default: {}      
      msdemo_nw_customer:
        aliases:
          - msdemo-db-customer  
networks:  
  msdemo_nw_customer:
    external:
      name: msdemo-nw-customer

