version: '3.7'
services:
  web-service-medication:  
    build:
      context: .
      target: web-service-medication
    image: msdemo-web-service-medication:v1.0  
    volumes:          
      - type: bind
        source: ./
        target: /medication    
    command:
      - /medication/run.sh   
    ports:
      - 6004:80
    environment:
      PYTHONUNBUFFERED: 1
      INSTALL_PATH: /medication
      FLASK_APP: app/medication.py
      FLASK_ENV: development     
      EVENT_BUS_IP: msdemo-event-bus      
      EVENT_BUS_USERNAME: msdemo_usr
      EVENT_BUS_PASSWORD: msdemo_pass
      DATABASE_NAME: medication.db     
    networks:
      default: {}
      msdemo_network:
        aliases:
          - msdemo-service-medication      
networks:
  msdemo_network:
    external:
      name: msdemo-nw
