version: '3.7'
services:
  web-service-order:  
    build:
      context: .
      target: web-service-order
    image: msdemo-web-service-order:v1.0  
    volumes:          
      - type: bind
        source: ./
        target: /order    
    command:
      - /order/build.sh
    ports:
      - 6003:80    
    environment:
      EVENT_BUS_IP: msdemo-event-bus      
      EVENT_BUS_USERNAME: msdemo_usr
      EVENT_BUS_PASSWORD: msdemo_pass
      DATABASE_IP: msdemo-db-order 
      DATABASE_PORT: 5432    
      DATABASE_NAME: order  
      DATABASE_USERNAME: order_usr
      DATABASE_PASSWORD: order_pass
    networks:
      default: {}
      msdemo-nw:
        aliases:
          - msdemo-service-order
      msdemo-nw-order:
        aliases:
          - msdemo-service-order      
networks:
  msdemo-nw:
    external:
      name: msdemo-nw
  msdemo-nw-order:
    external:
      name: msdemo-nw-order
  



