version: '3.7'
services:
  web_manager:
    build: .  
    image: msdemo-website-manager:v1.0  
    volumes:
      - '.:/app'
    ports:
      - 5002:80
    command:
      - /app/run.sh   
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: "app/app.py"
      FLASK_ENV: "development"
      SERVICE_REGISTRY: "http://msdemo-reverse-proxy/"
    networks:
      default: {}
      msdemo-nw:
        aliases:
          - msdemo-web-manager
networks:
  msdemo-nw:
    external:
      name: msdemo-nw