version: '3.7'
services:
  db-patient:
    restart: always
    build: 
      context: .
      target: db-patient
    image: msdemo-db-patient:v1.0
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${DB_PORT}:6379"
    volumes:          
      - type: bind
        source: ./data
        target: /data   
    networks:
      default: {}      
      msdemo_nw_patient:
        aliases:
          - msdemo-db-patient  
networks:  
  msdemo_nw_patient:
    external:
      name: msdemo-nw-patient

