version: '3.7'
services:
  web-service-patient:  
    build:
      context: .
      target: web-service-patient
    image: msdemo-web-service-patient:v1.0  
    volumes:          
      - type: bind
        source: ./
        target: /patient    
    command:
      - /patient/run.sh
    ports:
      - 6002:80    
    environment:
      PYTHONUNBUFFERED: 1
      INSTALL_PATH: /patient
      EVENT_BUS_IP: msdemo-event-bus      
      EVENT_BUS_USERNAME: msdemo_usr
      EVENT_BUS_PASSWORD: msdemo_pass
      DATABASE_IP: msdemo-db-patient
      DATABASE_PORT: 6379
      DATABASE_PASSWORD: patient_pass
    networks:
      default: {}
      msdemo-nw:
        aliases:
          - msdemo-service-patient
      msdemo-nw-order:
        aliases:
          - msdemo-service-patient
networks:
  msdemo-nw:
    external:
      name: msdemo-nw
  msdemo-nw-order:
    external:
      name: msdemo-nw-patient
