version: '3.7'
services:
  reverse-proxy: 
    build: .
    image: msdemo-reverse-proxy:v1.0    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/etc/nginx/html
    ports:
      - 80:80
      - 3000:3000
      - 4000:4000
    networks:
      default: {}
      msdemo-nw:
        aliases:
          - msdemo-reverse-proxy
networks:
  msdemo-nw:
    external:
      name: msdemo-nw