version: '3.7'
services:
  web-service-accounting:  
    build:
      context: .
      target: web-service-accounting
    image: msdemo-web-service-accounting:v1.0  
    volumes:          
      - type: bind
        source: ./
        target: /acccounting/
    command:
      - /acccounting/run.sh
    ports:      
      - 6001:80
    environment:               
      EVENT_BUS_IP: msdemo-event-bus      
      EVENT_BUS_USERNAME: msdemo_usr
      EVENT_BUS_PASSWORD: msdemo_pass         
      DATABASE_IP: msdemo-db-accounting
      DATABASE_NAME: accounting  
      ACCOUNTINGDB_USERNAME: accounting_usr
      ACCOUNTINGDB_PASSWORD: accounting_pass 
    networks:
      default: {}
      msdemo_network:
        aliases:
          - msdemo-service-accounting      
networks:
  msdemo_network:
    external:
      name: msdemo-nw
